name: 'commit to github'
description: 'Commits any changed files using GitHub API'
author: 'getsentry'
branding:
  icon: 'edit-3'
  color: 'purple'
inputs:
  github-token:
    description: 'GitHub token'
    required: false
    default: '${{ github.token }}'
  message:
    description: 'The commit message to use'
    required: false
    default: 'style(lint): Auto commit lint changes'
runs:
  using: 'node16'
  main: 'dist/index.js'
