name: "build"
on: pull_request

jobs:
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v3

    - name: yarn dist
      run: |
        yarn install
        yarn dist

    - name: exercise multifile behavior
      run: git rev-parse @ > latest-sha.txt

    - name: Use current action
      uses: ./
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        message: '[getsentry/action-github-commit] Auto commit build artifact'
